name: CICD pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: your-dockerhub-username/rapidcompetitions
  DOCKER_TAG: latest
  SKIP_TESTS: false
  SKIP_DOCKER_PUSH: false

jobs:
  test:
    if: env.SKIP_TESTS != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: env.SKIP_DOCKER_PUSH != 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ env.SKIP_DOCKER_PUSH != 'true' }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Deployment
        run: |
          echo "Build complete. Skipping actual deployment..."
          echo "This is a placeholder step for deployment."
