name: CICD pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        if: env.SKIP_TESTS != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        if: env.SKIP_TESTS != 'true'
        run: python manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Deployment
        run: |
          echo "Build complete. Skipping actual deployment..."
          echo "This is a placeholder step for deployment."
